### ISSUE TITLE
課題じゃんけん.cpp

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#1]
さすがに、ソースファイル名を全角文字はやめて下さい。
VisualStudioやUnity環境では問題にならないことが多いですが、
その他環境では、まだまだ全角文字は、問題になることが多いです。
ソースファイルの中のコメント以外の文字や、ソースファイル名など、
全角文字は使用しないで下さい。

**Comment by HikaProg** [comment]
修正完了いたしましたので、
更新してご確認お願いいたします。

**Comment by azuo0730** [comment]
確認できました。
こちらのイシューはクローズします。
