### ISSUE TITLE
struct Rand について２

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#11]
return min + (int)rand()*(max - min + 1) / (1 + RAND_MAX);
掛け算して割り算して．．．、ただ乱数取得するだけなのに、
色々重い処理しているように見えますが、そんなに演算必要ですか？

僕には、こんなに必要には思えないので、もう少し軽い処理にしてもらえますか。
何か意図やこだわりがあるのなら教えて下さい。

**Comment by HikaProg** [comment]
乱数取得方法を見直し、
修正いたしました。
確認お願いいたします。

**Comment by azuo0730** [comment]
あまり、一般的ではない気はしますが、問題ないです。
かなり精度の高い乱数を生成してくれそうなので、前よりよくなっていると思います。

ただ、別に rand関数を使うこと自体は問題なかったので、
minとmaxから欲しい乱数を取得する演算を、少し自分で考えては欲しかったですが．．．。

こちらはクローズします。
