### ISSUE TITLE
struct Result について

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#12]
これ、30試合より多く対戦した場合、どうなりますか？
考慮されてますか？

**Comment by HikaProg** [comment]
戦績を確認したら
現在の最新の戦績に更新するように
修正いたしました。
確認お願いいたします。

**Comment by azuo0730** [comment]
R押しても、戦績が出なくなっています。
確認をお願いします。

**Comment by HikaProg** [comment]
返信が遅くなり申し訳ありません。
Rボタンを押すと、最新の戦績から見て
指定数の戦績のみ表示するように修正いたしました。

**Comment by azuo0730** [comment]
問題なさそうです。
このチケットは終了とします。

お疲れ様でした。
