### ISSUE TITLE
ignore設定について

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#13]
ignore設定が足りていなくて、VisualStudioから出力された一時ファイルが、
Gitの作業ツリーに上がってきてます。
ちゃんとignore設定して下さい。

**Comment by HikaProg** [comment]
無駄なファイルを作業ツリーから除きました。
確認お願いいたします。

**Comment by azuo0730** [comment]
若干足りていない部分もなくはないですが、
おおよそ問題ないと思いますので、
こちらのチケットは終了とします。

お疲れ様でした。
