### ISSUE TITLE
classとstructの使い分けについて

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#14]
classとstructを器用に使いこなしているのですが、
何か意図があって、使い分けているのでしょうか？

C++では、一般的に、あまりstructは使わないイメージですが。

**Comment by HikaProg** [comment]
メンバ関数が1つ以下のものは構造体にして、
そのほかはクラスにしています。

**Comment by azuo0730** [comment]
#4 とは、だいぶ違う意見が書いてあるような気がしないでもないですが、
どんどん内容が似てしまったので、こちらはクローズします。

#4 に記載した件を確認しておいてください。
