### ISSUE TITLE
JANKEN_TYPEMAX について

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#2]
何故３なのか、根拠が薄いです。
また、グー・チョキ・パー、それぞれがどの数値に当てはまるのかも定義がなく分かりません。
enum にすれば、両方解決すると思います。

**Comment by HikaProg** [comment]
リテラルを消して
enumに変えました。

**Comment by azuo0730** [comment]
確認できました。
こちらのイシューはクローズします。
