### ISSUE TITLE
PCHについて

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#3]
おそらく、プロジェクトを新規作成した際に、勝手にできたのだと思うのですが、
PCH(プリコンパイルヘッダー)の意味、分かってますか？
何もヘッダーがないので、PCHの存在価値が何もないです。

PCHとは何か、僕に説明して下さい。

**Comment by HikaProg** [comment]
PCH(プリコンパイルヘッダー)...
処理高速化のためにヘッダファイルをコンパイルの最初にまとめて呼び出すヘッダファイルのこと。
ヘッダファイルのヘッダファイルのような認識であってますでしょうか。

必要なかったので、設定を見直しました。

**Comment by azuo0730** [comment]
ヘッダファイルのヘッダファイルではないです。
というか、意味がわかりません。

> 処理高速化のために

と、自分で書いてますが、これは、何の処理を高速化するのですか？

**Comment by HikaProg** [comment]
PCH(プリコンパイルヘッダー)...
インクルードされるヘッダファイルの再コンパイルを避けるためのファイルのこと。

コンパイル時のヘッダファイル呼び出しの高速化

**Comment by azuo0730** [comment]
そうです。
C++ではよく使われる方式です。
小さなプロジェクトでは逆に遅くなる場合もありますが、
大きいプロジェクトでは、まず間違いなく早くなるので、
大きなプロジェクトでは、使うことが多いです。
覚えておいてください。

こちらのチケットは終了とします。
お疲れ様でした。
