### ISSUE TITLE
structについて

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#4]
ほぼclassを使わず、structで構造体宣言をしていますが、
C++における、クラスと構造体の違いは、把握してますか？
メンバ関数も用意されており、一般的には、クラスを使う場面かと思いますが。

クラスと構造体の違いを、僕に説明して下さい。(このチケットに返信して下さい)
また、違いを理解した上で、クラスに変えるか、構造体のままにするか、選んでください。

**Comment by HikaProg** [comment]
構造体
・プリミティブ型に似た単一の値で構成されている
・頻繁にボックス化する必要がない
・データのサイズが小さい
・メンバ関数を扱うことは少ない

クラス
・構造体で挙げたものに当てはまらないとき

連想配列使ってするので
関数消して
構造体でします。

**Comment by azuo0730** [comment]
これ、意味分かって書いてます？
僕には、
> ・メンバ関数を扱うことは少ない

ここ以外、意味が分かりません。もう少し具体的に分かりやすく書いてもらえますか？
まさか、意味分からずコピペした訳ではないですよね？

> 連想配列使ってするので
関数消して
構造体でします。

ここも意味が分からないです。
連想配列関係ありますか？

**Comment by HikaProg** [comment]
構造体
・インスタンスの有効期間が短い
・メンバ関数を使うことは少ない
・継承などを使用する必要がない
クラス
・構造体で挙げたものに当てはまらないとき

>ここも意味が分からないです。
連想配列関係ありますか？

メンバ関数を減らして、
構造体にする意味合いを持たせようと
考え出た発言でしたが、
よく考えたら関係ありませんでした。

**Comment by azuo0730** [comment]
ここで議論しても永久に続きそうなので、いったん、僕なりの答えを記載します。

まず、答えてほしかったのは、C++言語として、構造体とクラスは何が違うか、です。
概念的な部分は、使い手によって答えが様々ですが、言語仕様としての違いは誰が答えても１つです。
まずは、それを理解していないと、概念的な部分の話に進めません。
まずは、言語仕様から、ちゃんと理解して下さい。

C++言語仕様上の構造体とクラスの違いは、以下の１つだけです
構造体
　・デフォルトのアクセシビリティがpublic
クラス
　・デフォルトのアクセシビリティがprivate

これだけです。

ここから、僕の考えでの、概念的な部分での、構造体とクラスの違いです。
構造体
　・直接メンバ変数にアクセスする使い方をするもの
　　例) Rectやベクトルなど、そのメンバ変数自体が意味をもつもの
クラス
　・メンバ変数を隠蔽し、自分のメンバは自分で面倒をみるもの
　　例) 各種ゲーム管理クラスやキャラ管理クラスなど、変数の中身を見なくても、関数を呼べば処理してくれるもの

こうつらつらと色々書いていますが、ぶっちゃけC++では、全部classでいいです。
どうしても構造体じゃないと気持ち悪いときがあるなら、使ってもらっても良いですが、
僕、個人的にはそんな場面はほとんどないです。

上記読んでみて、質問などあれば、返信して下さい。
「錦くんの言いたいことが僕に伝わっていないから、もっとちゃんと説明したい」
とかでも、返信してもらって大丈夫です。

問題なければ、クローズしてもらっても大丈夫です。
よろしくお願いします。

**Comment by HikaProg** [comment]
貴重な見解をありがとうございます。
私の考えは東さんの必要としていた
答えとはずれていました。
