### ISSUE TITLE
勝敗判定について

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#5]
string WinJudgeHand(string hand)
	{
		return ((hand == winHandStr) ? "勝ち！" : "");
	}
	string LoseJudgeHand(string hand)
	{
		return ((hand == loseHandStr) ? "負け..." : "");
	}
	string DrawJudgeHand(string hand)
	{
		return ((hand == myHandStr) ? "引き分け" : "");
	}

頑張って捻り出してくれたのは分かるんですが、
残念ながら、ただ単純に if文で書いたときより悪化しています。

string同士で == 比較していますけど、これは、int同士の == 比較に比べ、
圧倒的に重いです。
基本的にstringを使うのは、最終的に、エンドユーザに表示する時や、
その表示する文字列を作成する時、くらいです。
　(Unityだと、名前で検索とかもあるにはありますが、僕が名前検索が嫌いなのは、重いからです)

		judge += hand[myHandNum].DrawJudgeHand(hand[pcHandNum].myHandStr);
		judge += hand[myHandNum].WinJudgeHand(hand[pcHandNum].myHandStr);
		judge += hand[myHandNum].LoseJudgeHand(hand[pcHandNum].myHandStr);
同様に、stringの足し算も重いです。
むやみやたらに、３回も足し算してます。
　(この場合、"" という空文字を足しているので、重くないかも知れませんが、
　呼ばないに越したことはないです)

値の保持や判定などは、基本的に数値でやって下さい。
これは、C/C++に限らず、全てのプログラムにおいて、基本です。
string型を使うのは、基本的に表示したいときだけです。

**Comment by HikaProg** [comment]
勝敗判定を数値でできるように
修正しました。
ご確認お願いいたします。

**Comment by azuo0730** [comment]
概ねよくなっています。
if文を使うなという課題も、ちゃんとクリアできています。

しかし、結果が文字列で保持され、文字列でカウントされています。
結果も、ちゃんと数字で保持し、表示する時だけ、文字列にして下さい。

**Comment by HikaProg** [comment]
表示のタイミングだけ
文字列になるよう修正いたしました。
確認お願いいたします。

**Comment by azuo0730** [comment]
確認できました。
こちらのチケットはクローズします。

お疲れ様でした。
