### ISSUE TITLE
勝敗判定について２

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#6]
結局、? を使ってしまっているので、if文を使っているのと、やってることは一緒です。

? や switch も使わない方法を考えてみて下さい。
僕が常日頃から言っている、「処理はできるだけ少ない方が良い」に則ったものです。

まずは、#5 「勝敗判定について」 の
> 値の保持や判定などは、基本的に数値でやって下さい。
> これは、C/C++に限らず、全てのプログラムにおいて、基本です。
> string型を使うのは、基本的に表示したいときだけです。
を対応してから、こちらも考えてみて下さい。

自分の手(グー or チョキ or パー)と、
相手の手(グー or チョキ or パー)の、２つの値から、
勝敗結果(勝ち or 負け or 引き分け)の、１つの値を取得するイメージです。

**Comment by HikaProg** [comment]
?を使用しないような形に修正いたしました。
ご確認お願いいたします。

**Comment by azuo0730** [comment]
かなり難しく考えてくれていたようで、こちらはOKです。

もっとシンプルに、
２次元配列から取得するだけでも良いですよ。
