### ISSUE TITLE
リテラルについて

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#7]
int pcHandNum = rnd.GetRandom(0, 2);
0とは何ですか？
2とは何ですか？
#2 「JANKEN_TYPEMAX について」にも書きましたが、
enumでちゃんと定義して下さい。

基本的に、ソースコード中にリテラルが混じることは、ほぼないと思って下さい。

**Comment by HikaProg** [comment]
enumを配置いたしました。

**Comment by HikaProg** [comment]
enumを配置して修正いたしました。
確認お願いいたします。

**Comment by azuo0730** [comment]
OKです。
まだ少し、リテラル残ってますが、
まあ、許容範囲でしょう。
クローズします。
