### ISSUE TITLE
戦績表示について

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#8]
最初に僕が課題メールを送った時の仕様は以下です。

> ∇仕様
> １．プレイヤーに、キー入力で手を選ばせる
> 　0:未選択、1:グー、2:チョキ、3:パー
> ２．コンピュータの手を、ランダムで決定する
> ３．勝敗を表示する
> 　勝ち！ or 負け！
> ４．現在の戦績を表示する
> 　○勝×敗△引き分け
> ５．最初に戻る
履歴表示機能を付けてくれたのはありがたいですが、
> 　○勝×敗△引き分け
ができていません。
ちゃんと仕様をよく読んでから作って下さい。

**Comment by HikaProg** [comment]
戦績表示の部分を追加しました。
確認お願いいたします。

**Comment by azuo0730** [comment]
OKです。問題ないです。
強いて言うなら、Rが効かなくなってますが、修正するかは任せます。
このチケット自体はクローズします。
