### ISSUE TITLE
戦績表示について２

### ISSUE THREAD

**Issue by azuo0730** [HikaProg/janken#9]
Rを押して、戦績を表示すると、実行時エラーが出ていますが、
そちらでは出ていないですか？

何か、やばい系の操作してると思います。
配列外参照とかでしょうか。
確認お願いします。

**Comment by HikaProg** [comment]
配列外参照をおこしていたので
修正いたしました。

**Comment by azuo0730** [comment]
R押しても、戦績が出なくなっています。
確認をお願いします。

**Comment by HikaProg** [comment]
返信が遅くなり申し訳ありません。
Rボタンを押すと、最新の戦績から見て
指定数の戦績のみ表示するように修正いたしました。

**Comment by azuo0730** [comment]
問題なさそうです。
このチケットは終了とします。

お疲れ様でした。
